from .Bandit import Bandit
from .HIBL import HIBLAgent
from .IBL import IBLAgent
from .HRL import HRLAgent
from .RL import RLAgent
from .TS import TSAgent
from .HTS import HTSAgent
from .UCB import UCBAgent
from .HUCB import HUCBAgent